import type { Config } from "tailwindcss";

const config: Config = {
  // darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          text: "hsl(var(--primary-text))",
          50: "hsl(var(--primary-50))",
          100: "hsl(var(--primary-100))",
          150: "hsl(var(--primary-150))",
          200: "hsl(var(--primary-200))",
          250: "hsl(var(--primary-250))",
          300: "hsl(var(--primary-300))",
          400: "hsl(var(--primary-400))",
          500: "hsl(var(--primary-500))",
          600: "hsl(var(--primary-600))",
          700: "hsl(var(--primary-700))",
          800: "hsl(var(--primary-800))",
          850: "hsl(var(--primary-850))",
          900: "hsl(var(--primary-900))",
          950: "hsl(var(--primary-950))",
        },
        success: {
          DEFAULT: "#DAF5E8",
          50: "#C8EAD9",
          100: "#B5DECB",
          150: "#A3D3BC",
          200: "#91C8AD",
          300: "#6CB190",
          400: "#489B72",
          500: "#238455",
          600: "#1C6A44",
          700: "#154F33",
          800: "#0E3522",
          850: "#0B281A",
          900: "#071A11",
          950: "#040D09",
        },
        amber: {
          50: "#FEF7E6",
          100: "#FDEECC",
          150: "#FDE6B3",
          200: "#FCDD99",
          300: "#FACC66",
          400: "#F9BB33",
          500: "#F7AA00",
          600: "#C68800",
          700: "#946600",
          800: "#634400",
          850: "#4A3300",
          900: "#312200",
          950: "#191100",
        },
        info: {
          50: "#E9ECFB",
          100: "#D2D9F7",
          150: "#BCC7F3",
          200: "#A5B4EF",
          300: "#798EE6",
          400: "#4C69DE",
          500: "#1F43D6",
          600: "#1936AB",
          700: "#132880",
          800: "#0C1B56",
          850: "#091440",
          900: "#060D2B",
          950: "#030715",
        },
        warning: {
          50: "#FBEFE9",
          100: "#F7DFD2",
          150: "#F3D0BC",
          200: "#EFC0A5",
          300: "#E7A079",
          400: "#DF814C",
          500: "#D7611F",
          600: "#AC4E19",
          700: "#813A13",
          800: "#56270C",
          850: "#411D09",
          900: "#2B1306",
          950: "#160A03 ",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          50: "#F7EAEA",
          100: "#EED5D5",
          150: "#E6C0C0",
          200: "#DEABAB",
          300: "#CD8282",
          400: "#BD5858",
          500: "#AC2E2E",
          600: "#8A2525",
          700: "#671C1C",
          800: "#451212",
          850: "#340E0E",
          900: "#220909",
          950: "#110505",
        },
        neutral: {
          third: "#717171",
          50: "#EDEDED",
          100: "#DBDBDB",
          150: "#CACACA",
          200: "#B8B8B8",
          300: "#949494",
          400: "#717171",
          500: "#4D4D4D",
          600: "#3E3E3E",
          700: "#2E2E2E",
          800: "#1F1F1F",
          850: "#171717",
          900: "#0F0F0F",
          950: "#080808",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderWidth: {
        6: "6px",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "collapsible-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-collapsible-content-height)",
          },
        },
        "collapsible-up": {
          from: {
            height: "var(--radix-collapsible-content-height)",
          },
          to: {
            height: "0",
          },
        },
        slideIn: {
          from: {
            opacity: "0",
            transform: "translateY(-6px)",
          },
          to: {
            opacity: "1",
            transform: " translateY(0)",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.25s ease-out",
        "accordion-up": "accordion-up 0.25s ease-out",
        "collapsible-down": "collapsible-down 0.2s ease-out",
        "collapsible-up": "collapsible-up 0.2s ease-out",
        "error-message": "slideIn 0.2s ease-in forwards",
      },
    },
  },
  plugins: [],
};
export default config;
