export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: "شامل است", value: "iLike" as const },
    { label: "شامل نیست", value: "notILike" as const },
    { label: "برابر است", value: "eq" as const },
    { label: "برابر نیست", value: "ne" as const },
    { label: "خالی است", value: "isEmpty" as const },
    { label: "خالی نیست", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "برابر است", value: "eq" as const },
    { label: "برابر نیست", value: "ne" as const },
    { label: "کوچکتر از", value: "lt" as const },
    { label: "کوچکتر یا برابر با", value: "lte" as const },
    { label: "بزرگتر از", value: "gt" as const },
    { label: "بزرگتر یا برابر با", value: "gte" as const },
    { label: "بین دو مقدار", value: "isBetween" as const },
    { label: "خالی است", value: "isEmpty" as const },
    { label: "خالی نیست", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "برابر است", value: "eq" as const },
    { label: "برابر نیست", value: "ne" as const },
    { label: "قبل از", value: "lt" as const },
    { label: "بعد از", value: "gt" as const },
    { label: "برابر یا قبل از", value: "lte" as const },
    { label: "برابر یا بعد از", value: "gte" as const },
    { label: "بین دو تاریخ", value: "isBetween" as const },
    { label: "نسبت به امروز", value: "isRelativeToToday" as const },
    { label: "خالی است", value: "isEmpty" as const },
    { label: "خالی نیست", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "برابر است", value: "eq" as const },
    { label: "برابر نیست", value: "ne" as const },
    { label: "خالی است", value: "isEmpty" as const },
    { label: "خالی نیست", value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: "شامل هرکدام از موارد", value: "inArray" as const },
    { label: "شامل هیچ‌کدام از موارد نیست", value: "notInArray" as const },
    { label: "خالی است", value: "isEmpty" as const },
    { label: "خالی نیست", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "برابر است", value: "eq" as const },
    { label: "برابر نیست", value: "ne" as const },
  ],
  sortOrders: [
    { label: "صعودی", value: "asc" as const },
    { label: "نزولی", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
};
