import NotificationProvider from "@/provider/NotificationProvider";
import EnvClientProvider from "@/provider/env-client-provider";
import QueryClientProvider from "@/provider/queryClientProvider";
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";
import { iransansfanum } from "@/lib/iransans-font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${iransansfanum.className} antialiased`} dir="rtl">
        <EnvClientProvider>
          <QueryClientProvider>
            <NotificationProvider>
              <NuqsAdapter>{children}</NuqsAdapter>
            </NotificationProvider>
          </QueryClientProvider>
        </EnvClientProvider>
      </body>
    </html>
  );
}
